name: PiggyCustomEnchants
main: DaPigGuy\PiggyCustomEnchants\PiggyCustomEnchants
version: 2.1.7
api: [3.11.2, 4.0.0]
load: POSTWORLD
author: DaPigGuy
permissions:
  piggycustomenchants:
    default: false
    description: "Allows usage of all PiggyCustomEnchants features"
    children:
      piggycustomenchants.command:
        default: op
        description: "Allow usage of all PiggyCustomEnchants commands"
        children:
          piggycustomenchants.command.ce:
            default: op
            description: "Allow usage of the /customenchant command"
            children:
              piggycustomenchants.command.ce.about:
                default: true
                description: "Allow usage of the /customenchant about subcommand"
              piggycustomenchants.command.ce.enchant:
                default: op
                description: "Allow usage of the /customenchant enchant subcommand"
              piggycustomenchants.command.ce.help:
                default: true
                description: "Allow usage of the /customenchant help subcommand"
              piggycustomenchants.command.ce.info:
                default: true
                description: "Allow usage of the /customenchant info subcommand"
              piggycustomenchants.command.ce.list:
                default: true
                description: "Allow usage of the /customenchant list subcommand"
